### ISSUE TITLE
`CompoundMultiIndex` returns duplicate entries with `SingleIndexer`s

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/go-memdb#95]
I'm not 100% sure this (mis)behaviour can be attributed to the combination of `CompoundMultiIndex` and single indexers actually, but I have a repro case which looks simple enough that it's hard to find any other cause there.

```go
&memdb.CompoundMultiIndex{
	Indexes: []memdb.Indexer{
		&memdb.StringFieldIndex{Field: "Address"},
		&memdb.StringFieldIndex{Field: "Version"},
	},
	AllowMissing: true,
}
```
when a single entry is inserted into a table with such an index:

```go
txn.Insert("providers", &entry{
	Address: "aws",
	Version: "1.0.0",
})
```
and subsequently looked up (in a separate transaction)
```go
txn.Get("providers", "provider")
```
then the same entry is returned twice:

```
&entry{Address:"aws", Version:"1.0.0"}
&entry{Address:"aws", Version:"1.0.0"}
```

I can confirm it is the _exact_ same entry by comparing the pointer address, which consequently also makes such index impossible to use in `DeleteAll` where each individual entry would be looked up again via `id` index (as part of `Delete`) while iterating over results and (obviously) the second duplicate no longer exists once the first (original) entry is deleted, so `DeleteAll` then returns "not found" error.

https://github.com/hashicorp/go-memdb/blob/542a5804dedaaddf1a0cad8b6a7b0b3fcf438776/txn.go#L313-L329

Here is a full repro case:

 - https://gist.github.com/radeksimko/44d205695c70428a7029b7326d917365
 - https://play.golang.org/p/STVtJ4M-bcO

**Comment by dnephin** [comment]
This may have been fixed by #108, it sounds related.

**Comment by radeksimko** [comment]
According to the [attached repro case](https://gist.github.com/radeksimko/44d205695c70428a7029b7326d917365) it looks like it was not fixed yet

```sh
➜  go get github.com/hashicorp/go-memdb@422653b
go: downloading github.com/hashicorp/go-memdb v1.3.3-0.20211105203423-422653bbb902
go get: upgraded github.com/hashicorp/go-memdb v1.3.2 => v1.3.3-0.20211105203423-422653bbb902
➜ go mod tidy
➜ go run main.go
entry: &main.entry{Address:"aws", Version:"1.0.0"}
entry: &main.entry{Address:"aws", Version:"1.0.0"}
```
